const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const dashboard = fs.readFileSync(path.join(root, "dashboard.js"), "utf8");
const editor = fs.readFileSync(path.join(root, "public-site.js"), "utf8");
const template = fs.readFileSync(path.join(root, "website-template.js"), "utf8");
assert.match(dashboard, /templates\.buildWebsiteContent/);
assert.match(dashboard, /saveWebsiteDraft/);
assert.match(dashboard, /publishWebsiteDraft/);
assert.match(dashboard, /listRegistrations/);
assert.match(dashboard, /Website Views[\s\S]*<strong>—<\/strong>/);
assert.match(dashboard, /\["duplicate","Duplicate"\]/);
assert.match(dashboard, /\["toggle",item\.published/);
assert.match(dashboard, /\["delete","Delete"\]/);
assert.match(dashboard, /data-class-form/);
assert.match(dashboard, /uploadBusinessMedia/);
assert.match(dashboard, /highlighted/);
assert.doesNotMatch(dashboard, /edit=classes&new=1/);
assert.match(editor, /data-editor-nav="\$\{key\}"/);
assert.match(editor, /\["classes", "Classes"\]/);
assert.match(editor, /data-owner-edit.*openEditor\("hero"\)/);
assert.match(editor, /openEditor\(requestedEditor \|\| "hero"\)/);
assert.doesNotMatch(editor, /data-owner-edit.*openEditor\("classes"\)/, "Edit Website must open the general editor, not jump straight to classes");
assert.match(editor, /data-move-gallery/);
assert.match(editor, /data-remove-gallery/);
assert.match(editor, /uploadBusinessMedia/);
assert.match(template, /content\.classes\.filter\(\(item\) => item\.published !== false\)/);
assert.match(template, /data-book-class/);
assert.match(editor, /createRegistration/);
assert.match(editor, /Pay .* with Venmo/);
// Nav tabs with no real feature behind them must say so, not link to a dead editor section.
assert.match(dashboard, /UNBUILT_VIEWS = new Set\(\["instructors", "reviews", "analytics"\]\)/);
assert.doesNotMatch(dashboard, /edit=\$\{title\.toLowerCase\(\)\}/, "unbuilt tabs must not link to a website-editor section that does not exist");
assert.match(dashboard, /comingSoon\("Instructors"/);
assert.match(dashboard, /comingSoon\("Reviews"/);
assert.match(dashboard, /comingSoon\("Analytics"/);
assert.match(dashboard, /placeholder\("Social", "social"\)/, "Social is a real editor section and should keep its working link");
// Class/registration search+filter must preserve the class's real array index, or actions
// (edit/duplicate/toggle/delete) target the wrong class once the list is filtered.
assert.match(dashboard, /const filteredClasses = \(\) => classes\(\)\.map\(\(item, index\) => \(\{ item, index \}\)\)/);
assert.match(dashboard, /list\.map\(\(\{ item, index \}\) => row\(item, index\)\)/);
assert.match(dashboard, /data-class-search/);
assert.match(dashboard, /data-registration-search/);
console.log("owner dashboard regression tests passed");
