const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const dashboard = fs.readFileSync(path.join(root, "dashboard.js"), "utf8");
const editor = fs.readFileSync(path.join(root, "public-site.js"), "utf8");
const template = fs.readFileSync(path.join(root, "website-template.js"), "utf8");
assert.match(dashboard, /templates\.buildWebsiteContent/);
assert.match(dashboard, /saveWebsiteDraft/);
assert.match(dashboard, /publishWebsiteDraft/);
assert.match(dashboard, /Registration data will appear after booking is connected/);
assert.match(dashboard, /Website Views[\s\S]*<strong>—<\/strong>/);
assert.match(dashboard, /data-class-action="duplicate"/);
assert.match(dashboard, /data-class-action="toggle"/);
assert.match(dashboard, /data-class-action="delete"/);
assert.match(editor, /data-editor-nav="\$\{key\}"/);
assert.match(editor, /\["classes", "Classes"\]/);
assert.match(editor, /openEditor\("classes"\)/);
assert.match(editor, /data-move-gallery/);
assert.match(editor, /data-remove-gallery/);
assert.match(editor, /uploadBusinessMedia/);
assert.match(template, /content\.classes\.filter\(\(item\) => item\.published !== false\)/);
console.log("owner dashboard regression tests passed");
