const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const dashboard = fs.readFileSync(path.join(root, "dashboard.js"), "utf8");
const editor = fs.readFileSync(path.join(root, "public-site.js"), "utf8");
const template = fs.readFileSync(path.join(root, "website-template.js"), "utf8");
assert.match(dashboard, /templates\.buildWebsiteContent/);
assert.match(dashboard, /saveWebsiteDraft/);
assert.match(dashboard, /publishWebsiteDraft/);
assert.match(dashboard, /listRegistrations/);
assert.match(dashboard, /Website Views[\s\S]*<strong>—<\/strong>/);
assert.match(dashboard, /\["duplicate","Duplicate"\]/);
assert.match(dashboard, /\["toggle",item\.published/);
assert.match(dashboard, /\["delete","Delete"\]/);
assert.match(dashboard, /data-class-form/);
assert.match(dashboard, /uploadBusinessMedia/);
assert.match(dashboard, /highlighted/);
assert.doesNotMatch(dashboard, /edit=classes&new=1/);
assert.match(editor, /data-editor-nav="\$\{key\}"/);
assert.match(editor, /\["classes", "Classes"\]/);
assert.match(editor, /openEditor\("classes"\)/);
assert.match(editor, /data-move-gallery/);
assert.match(editor, /data-remove-gallery/);
assert.match(editor, /uploadBusinessMedia/);
assert.match(template, /content\.classes\.filter\(\(item\) => item\.published !== false\)/);
assert.match(template, /data-book-class/);
assert.match(editor, /createRegistration/);
assert.match(editor, /Pay .* with Venmo/);
console.log("owner dashboard regression tests passed");
